### ISSUE TITLE
Feature: In "Job Levels" matrix, highlight selected row and column.

### ISSUE THREAD

**Issue by Raijinili** [Glain/FFTPatcher#11]
Would make it a lot easier to identify this:
![image](https://user-images.githubusercontent.com/2422807/85218294-0380d680-b367-11ea-9456-3f0358fa532b.png)

Also, maybe increase visibility of nonzero entries compared to zero entries Or color-scale them.

**Comment by Glain** [comment]
Addressed in commit 9aad110.
