### ISSUE TITLE
[FFTorgASM] Bug: space no longer toggles selected patch

### ISSUE THREAD

**Issue by AndruC** [Glain/FFTPatcher#12]
In 492 I used to be able to use the arrow keys to run down an XML file and hit space to toggle patches on/off. 

I can still use the arrow keys to navigate the list but I can't toggle anymore with the spacebar.

**Comment by Glain** [comment]
Should be fixed with commit https://github.com/Glain/FFTPatcher/commit/24c6a2e524ac79a737afb5c10a670339ab86c00a.  It should be part of the next beta release.

**Comment by Glain** [comment]
Issue re-emerged, but re-fixed with commit d77a11a.
