### ISSUE TITLE
Type-to-search on main lists does not reset often enough

### ISSUE THREAD

**Issue by Raijinili** [Glain/FFTPatcher#15]
On lists like this:
![image](https://user-images.githubusercontent.com/2422807/143667167-3e76a1fc-8e65-40b3-b679-ced8f27def04.png)
Type-to-search does not reset unless you click on a value field and then click back on the list.

It should reset:
- After a timeout.
- When clicking/right-clicking on an element of the list.
- When clicking at all, actually.
- When focus is changed. For example, it does not reset when navigating the top menu (e.g. "File").

**Comment by Glain** [comment]
Should be fixed with commit 61f6c2c.
