### ISSUE TITLE
Weapons should say just "Inflict Status" when using a status proc formula

### ISSUE THREAD

**Issue by Raijinili** [Glain/FFTPatcher#16]
If the weapon has formula 1, it shows "Inflict Status/Cast Spell".
![image](https://user-images.githubusercontent.com/2422807/143670064-db095e76-9f46-4a80-9430-d2fa7aa05a31.png)

However, if it has formula 2, it shows "Ability" instead.
![image](https://user-images.githubusercontent.com/2422807/143670073-f83e2569-ee27-416c-b8ac-b2a1c174fb08.png)

That means the "/Cast Spell" part is redundant, because when the field is interpreted as a spell, that text gets replaced anyway.

Also, it is misleading because "Inflict Status/Cast Spell" is a clickable link, and the link goes to the Inflict Status list, not the ability list.

**Comment by Glain** [comment]
Should be fixed with commit 98124f5.
