### ISSUE TITLE
Shishi: Silently fails to patch sprite pngs created by other tools

### ISSUE THREAD

**Issue by invadermonks** [Glain/FFTPatcher#24]
Shishi give the following result trying to patch 30 sprite pngs converted from BMP to PNG from TLW resources:

start /wait "Patch" ShishiSpriteEditor.exe -expand -patch "data\bugtest2\shishi_import" "output\fft_1685390769.bin"
2 sprites imported.

These patch fine as BMPs (giving 30 sprites imported) but converting them to PNGs causes only 2 to import, and gives no error message - so something is awry with png handling.

[bugtest2_shishi_import.zip](https://github.com/Glain/FFTPatcher/files/11593974/bugtest2_shishi_import.zip)

**Comment by Glain** [comment]
@invadermonks There is now a more verbose logging of errors with commit c668a9a.  The PNGs in the input file, save for 2, are in the wrong format.  Some are 4bpp, and others seem to have no image data whatsoever and display as 1bpp.  Sprites are expected to be imported from command line as 8bpp.

**Comment by invadermonks** [comment]
Good to know, I'll make sure my pngs are in the proper formats, thanks for the descriptive error messages now!
